#端口
server.port: 8887
spring.application.name: dbdemo

# mysql
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    #数据库1
    db1:
      jdbc-url: jdbc:mysql://127.0.0.1:3306/itsm_zhfy?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&useSSL=false
      username: root
      password: root
    #数据库2
    db2:
      jdbc-url: jdbc:mysql://192.168.0.36:3306/bsm?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&useSSL=false
      username: root
      password: zanyue$2012


# mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml